### ISSUE TITLE
Clearly a virus 

### ISSUE THREAD

**Issue by Lillythefox** [EclipsesDev/EclipseWare#3]
This is clearly a virus as shown by a virustotal scan!
The results show that this is the Wacatac trojan not just a roblox hack.
And before you say "they always show as viruses" they show as hack tools not trojans!

DO NOT DOWNLOAD!!

**Comment by EclipsesDev** [comment]
> This is clearly a virus as shown by a virustotal scan! The results show that this is the Wacatac trojan not just a roblox hack. And before you say "they always show as viruses" they show as hack tools not trojans!
> 
> DO NOT DOWNLOAD!!

imagin trying to be smart.. go virustotal fluxis and krnl.. they have more detection but its safe.. so before you try to complain something dumb think again and use your brain kid

**Comment by EclipsesDev** [comment]
false information

**Comment by Lillythefox** [comment]
Why not make it open source then for us to see the code?

**Comment by EclipsesDev** [comment]
> Why not make it open source then for us to see the code?

are you dumb or smth? the one that gets detected for virus is only the dll... and the dll is belong to wearedevs and you can see they are trusted but if you still wanna act dumb then try contacting their support

**Comment by Lillythefox** [comment]
Why come on you dont like FOSS

**Comment by EclipsesDev** [comment]
> Why come on you dont like FOSS

Case close don't try asking anymore questions, just ask in our discord support, if you still wanna be stubborn
