### ISSUE TITLE
Clearly Virus

### ISSUE THREAD

**Issue by Blake1of5** [EclipsesDev/EclipseWare#8]
they admitted on discord after i called them out lol. calling me stupid and saying i shouldve checked their stars on github lol. do not fall for these poor skids tryna make a little bit of cash

**Comment by Franzoli-GitHub** [comment]
Its literally open source hahahahhahah bruh u tripin 
Thats why its called FOS. Sorry but your the skid that feaked out in discord cuz u couldn't look at the source code

And btw prove to us how is it a virus when the source code CAN BE VIEWED BY ANYONE. Meaning if your brain cells are still working u can see the code and see how it works, and someone already forked it with a already working prototype 
So its not incomplete and the source code is there and it works

**Comment by Blake1of5** [comment]
> 

Lol your discord team got blatant lol. they literally admitted but okay.

**Comment by Franzoli-GitHub** [comment]
> > 
> 
> Lol your discord team got blatant. they literally admitted but okay.

if you mean admitted to you that you were wrong then yes we admitted that your claims are bullshit and it honestly ruined my morning.
