### ISSUE TITLE
AV Marked it as abunch of trojans and malware?

### ISSUE THREAD

**Issue by Mackazo** [EclipsesDev/EclipseWare#9]
My AV marked it as abunch trojans and stuff any help???

**Comment by Franzoli-GitHub** [comment]
To explain it real short av's hate executors may it be synapse or krnl or eclipseware but there not a virus but the av's think so.

**Comment by EclipsesDev** [comment]
yes any antivirus will detect executor like all executor as a malware / virus.. but it is totally only a false detection.. so don't worry about it 👌

**Comment by EclipsesDev** [comment]
false detection
